In [2]:
# "numpy"-- number pyhton.

In [4]:
import numpy as np

In [4]:
l = [1,2,3,4,4]

In [5]:
type(l)

list

In [6]:
a = np.array(l)

In [7]:
a

array([1, 2, 3, 4, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [10]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [12]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a.ndim # ndim --- dimension

1

In [14]:
a1.ndim # no. [] present the number of dimensions

2

In [15]:
a2.ndim

3

In [21]:
a3 = np.array([[[1,2,3],[4,0.5,6]],[[1,2,3],[4,0.5,6]],[[1,2,3],[4,0.5,6]]])

In [22]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [23]:
a3.ndim

3

In [2]:
l = [1,2,3,4]

In [5]:
np.asarray(l)

array([1, 2, 3, 4])

In [6]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [7]:
a=np.asarray(l)

In [8]:
m =np.matrix(l)

In [9]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [10]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a1 = a # SOLO COPY

In [13]:
a1

array([1, 2, 3, 4])

In [14]:
a

array([1, 2, 3, 4])

In [16]:
a[0] = 10

In [17]:
a

array([10,  2,  3,  4])

In [18]:
a1 # here also the value has changed from a to a1

array([10,  2,  3,  4])

In [19]:
a1[3] = 50 # THIS IS THE EXAMPLE OF "SOLO COPY".

In [20]:
a1

array([10,  2,  3, 50])

In [21]:
a

array([10,  2,  3, 50])

In [22]:
a2 = np.copy(a) # ----- DEEP COPY 

In [23]:
a2

array([10,  2,  3, 50])

In [24]:
a2[2] = 30 #THIS IS THE EXAMPLE OF "DEEP COPY".

In [25]:
a2

array([10,  2, 30, 50])

In [26]:
a # here the value is not chnaged as above

array([10,  2,  3, 50])

In [27]:
np.fromfunction(lambda i,j : i ==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [28]:
np.random.rand(2,3) ## very very useful function....

array([[0.13920079, 0.94414811, 0.06094888],
       [0.00853129, 0.85850882, 0.24637563]])

In [29]:
np.random.rand(2,3,2)

array([[[7.32807583e-02, 2.67119221e-01],
        [7.42038172e-01, 1.79094569e-04],
        [1.23664205e-02, 1.62189929e-01]],

       [[4.94944360e-01, 2.14424975e-01],
        [9.94930078e-01, 4.62944208e-01],
        [4.57911528e-01, 7.80412039e-01]]])

In [30]:
np.random.rand(2,3,2,2)

array([[[[0.67246718, 0.44018646],
         [0.82062492, 0.25846387]],

        [[0.64981358, 0.28299662],
         [0.8197457 , 0.52686758]],

        [[0.96300901, 0.51661672],
         [0.00471097, 0.82585893]]],


       [[[0.73463419, 0.68518294],
         [0.25187772, 0.37714207]],

        [[0.63550682, 0.06394052],
         [0.81766074, 0.76982036]],

        [[0.73486034, 0.34063724],
         [0.58718235, 0.73430453]]]])

In [31]:
np.random.rand(1,4,4)

array([[[0.22978047, 0.72800478, 0.86376494, 0.97616216],
        [0.63527636, 0.04215615, 0.7859068 , 0.79843895],
        [0.68549613, 0.32057985, 0.6371145 , 0.20308194],
        [0.64168046, 0.8433005 , 0.7833222 , 0.93663572]]])

In [32]:
np.random.rand(2,4,4)

array([[[0.05540792, 0.95644601, 0.10058052, 0.87571847],
        [0.89019839, 0.90770805, 0.74350085, 0.86637655],
        [0.62568111, 0.04511795, 0.45923386, 0.71242674],
        [0.06193779, 0.74428017, 0.07189435, 0.67245992]],

       [[0.02894042, 0.2585209 , 0.16181998, 0.56524437],
        [0.61624825, 0.02579911, 0.01064898, 0.8580439 ],
        [0.59510232, 0.11618799, 0.10654045, 0.6714624 ],
        [0.31093015, 0.06875247, 0.33786952, 0.4531975 ]]])

In [33]:
np.random.randn(3,4,4)

array([[[ 0.68518906, -0.87337581, -1.48058564, -0.03025735],
        [ 0.52695761,  0.25030095, -0.76859175,  1.0395705 ],
        [-1.03041397,  1.3702495 , -0.57995231, -0.54715072],
        [-0.30357512, -0.71699469, -1.42647357, -0.34191051]],

       [[ 0.67913689,  0.64721913,  0.77151863,  0.189522  ],
        [ 0.02572973, -0.36795072, -1.23753089,  0.67749556],
        [ 1.31948335,  0.50772932, -0.62211576, -0.53361923],
        [-0.83643269, -0.32252983,  0.51275502, -0.01315384]],

       [[-0.9680714 , -0.90678971, -0.02785065,  0.69112152],
        [-2.01352731,  0.30905699,  0.48708039, -1.96038252],
        [ 0.06616349,  0.0120024 , -0.26106731,  1.31561869],
        [ 0.68609742,  0.56043652, -0.03742232, -0.8994712 ]]])

In [36]:
np.random.randint(0,10,(4,4,2))

array([[[7, 8],
        [6, 0],
        [4, 9],
        [8, 3]],

       [[4, 3],
        [3, 0],
        [7, 2],
        [2, 2]],

       [[2, 7],
        [8, 4],
        [3, 8],
        [1, 6]],

       [[6, 5],
        [2, 2],
        [6, 5],
        [1, 5]]])

In [37]:
d = np.random.randn(3,4)

In [40]:
import pandas as pd

In [41]:
pd.DataFrame(d)

0         1         2         3
0 -0.410227 -0.890203 -1.140445  1.825861
1  0.716978  0.454763  1.110854  0.447158
2  0.628037  0.836998  0.283757  1.297982

In [42]:
d1 = np.random.randint(0,10,(4,4,2)) # here data size = 4*4*2 = 32 so we have to reshape according to 32 only

In [44]:
d1.reshape(16,2)

array([[0, 0],
       [4, 2],
       [3, 1],
       [4, 6],
       [8, 2],
       [4, 4],
       [7, 3],
       [4, 8],
       [3, 2],
       [8, 8],
       [4, 9],
       [9, 7],
       [4, 6],
       [8, 1],
       [4, 6],
       [5, 1]])

In [45]:
d1.reshape(8,4)

array([[0, 0, 4, 2],
       [3, 1, 4, 6],
       [8, 2, 4, 4],
       [7, 3, 4, 8],
       [3, 2, 8, 8],
       [4, 9, 9, 7],
       [4, 6, 8, 1],
       [4, 6, 5, 1]])

In [46]:
d1.reshape(8,-1) # here 8 is mul of 32 and -1 is the missing value it wil automatically asssign

array([[0, 0, 4, 2],
       [3, 1, 4, 6],
       [8, 2, 4, 4],
       [7, 3, 4, 8],
       [3, 2, 8, 8],
       [4, 9, 9, 7],
       [4, 6, 8, 1],
       [4, 6, 5, 1]])

In [47]:
d1.reshape(8,-15649874)

array([[0, 0, 4, 2],
       [3, 1, 4, 6],
       [8, 2, 4, 4],
       [7, 3, 4, 8],
       [3, 2, 8, 8],
       [4, 9, 9, 7],
       [4, 6, 8, 1],
       [4, 6, 5, 1]])

In [48]:
d1.reshape(2,-15479)

array([[0, 0, 4, 2, 3, 1, 4, 6, 8, 2, 4, 4, 7, 3, 4, 8],
       [3, 2, 8, 8, 4, 9, 9, 7, 4, 6, 8, 1, 4, 6, 5, 1]])

In [49]:
# now we can convert into data frame.

In [50]:
pd.DataFrame(d1.reshape(32,-1215646)) # Data frame is always a 2 dimension.

0
0   0
1   0
2   4
3   2
4   3
5   1
6   4
7   6
8   8
9   2
10  4
11  4
12  7
13  3
14  4
15  8
16  3
17  2
18  8
19  8
20  4
21  9
22  9
23  7
24  4
25  6
26  8
27  1
28  4
29  6
30  5
31  1

In [ ]:
import numpy as np

In [ ]:
range(10)

In [1]:
# 4th Feb Class - Numpy and Graphs:

In [58]:
import numpy as np

In [5]:
range(10) # generator function

range(0, 10)

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# Range() can only take interger is cant generate float  so,

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [13]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [14]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [15]:
# Line space function:-

In [16]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [17]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [18]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
np.ones((3,4,2)) +5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [26]:
np.ones((3,4,2)) *5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [28]:
np.empty((2,3))

array([[4.6903578e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [29]:
np.eye(4) # all diagonal elements are 1 == identity matrices.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
a = np.eye(4)

In [31]:
a.shape

(4, 4)

In [32]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
a.size

16

In [35]:
a.ndim

2

In [36]:
a1 = np.random.randn(3,4)

In [37]:
a1

array([[-0.32828458,  0.75195717, -1.36309857,  1.27559764],
       [ 0.48971984,  0.61315143,  0.1380955 , -1.47554737],
       [ 2.02652925, -0.06715453,  2.51674343,  0.55609107]])

In [38]:
import pandas as pd

In [39]:
pd.DataFrame(a1)

0         1         2         3
0 -0.328285  0.751957 -1.363099  1.275598
1  0.489720  0.613151  0.138096 -1.475547
2  2.026529 -0.067155  2.516743  0.556091

In [40]:
a1

array([[-0.32828458,  0.75195717, -1.36309857,  1.27559764],
       [ 0.48971984,  0.61315143,  0.1380955 , -1.47554737],
       [ 2.02652925, -0.06715453,  2.51674343,  0.55609107]])

In [41]:
# If we want to extract any data from this array (in pandas we can use loc() but here),

In [42]:
a1[1][1] # Here if we want to extract 0.61315143 which is situated at Row = 1 and column = 1 

0.6131514272730242

In [44]:
a1[0:2, 0:2]

array([[-0.32828458,  0.75195717],
       [ 0.48971984,  0.61315143]])

In [45]:
a1[[0,1], 0:2]

array([[-0.32828458,  0.75195717],
       [ 0.48971984,  0.61315143]])

In [46]:
a1

array([[-0.32828458,  0.75195717, -1.36309857,  1.27559764],
       [ 0.48971984,  0.61315143,  0.1380955 , -1.47554737],
       [ 2.02652925, -0.06715453,  2.51674343,  0.55609107]])

In [47]:
a1[[1,2],3]

array([-1.47554737,  0.55609107])

In [59]:
m1= np.random.randint(1,3,(3,3))

In [60]:
m1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [61]:
m2= np.random.randint(2,4,(3,3))

In [62]:
m2

array([[3, 2, 2],
       [3, 3, 3],
       [2, 3, 2]])

In [63]:
m1*m2 # its just a element wise multiplication not matrix multiplication.

array([[3, 4, 4],
       [3, 3, 6],
       [4, 3, 2]])

In [54]:
# So, for matrix multiplication.

In [64]:
m1@m2   # Matrix Multiplication.

array([[13, 14, 12],
       [10, 11,  9],
       [11, 10,  9]])

In [65]:
m1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [67]:
# Findout power function for each element? 

In [68]:
pow(m1,2)

array([[1, 4, 4],
       [1, 1, 4],
       [4, 1, 1]])

In [69]:
pow(m1,4)

array([[ 1, 16, 16],
       [ 1,  1, 16],
       [16,  1,  1]])

In [70]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [71]:
np.log(m1)

array([[0.        , 0.69314718, 0.69314718],
       [0.        , 0.        , 0.69314718],
       [0.69314718, 0.        , 0.        ]])

In [72]:
np.log10(m1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [73]:
np.exp(m1) #Exponential function.

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [74]:
m1**2

array([[1, 4, 4],
       [1, 1, 4],
       [4, 1, 1]])

In [ ]:
#_----------------------End-------------  (57.40)