In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig
from numpy.linalg import eig

In [3]:
data = np.array([[3,4],[2,8],[6,9],[10,12]])

In [4]:
data

array([[ 3,  4],
       [ 2,  8],
       [ 6,  9],
       [10, 12]])

In [6]:
df = pd.DataFrame(data,columns=["math","Bio"])

In [7]:
df

math  Bio
0     3    4
1     2    8
2     6    9
3    10   12

In [8]:
plt.scatter(df["math"],df["Bio"])

Steps of PCA:

1. Standarization of data
2. find covariance matrix from the data
3.eig value and eig vector
4.find the principle component

In [9]:
meanbycol = np.mean(data,axis=0)

In [10]:
meanbycol

array([5.25, 8.25])

In [11]:
# 1.
scaled_data = data-meanbycol

In [12]:
scaled_data

array([[-2.25, -4.25],
       [-3.25, -0.25],
       [ 0.75,  0.75],
       [ 4.75,  3.75]])

In [14]:
stdbycol = np.std(data,axis=0)

In [15]:
stdbycol

array([3.1124749 , 2.86138079])

In [16]:
scaled_data=scaled_data/stdbycol

In [17]:

scaled_data

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])

In [18]:
from sklearn.preprocessing import StandardScaler

st = StandardScaler()
st.fit_transform(df)

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])

In [19]:

scaled_data.T

array([[-0.7228974 , -1.04418513,  0.2409658 ,  1.52611672],
       [-1.4852969 , -0.08737041,  0.26211122,  1.31055608]])

In [22]:
# 2.
cov_mat=np.cov(scaled_data.T)

In [23]:
cov_mat

array([[1.33333333, 1.07605651],
       [1.07605651, 1.33333333]])

In [25]:
# 3.
eig_value,eig_vector = eig(cov_mat)

In [26]:
eig_vector

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [27]:
eig_value

array([2.40938985, 0.25727682])

In [24]:
scaled_data

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])

In [33]:
eig_vector.T.dot(scaled_data.T).T              # Line 1

array([[-1.56142916, -0.53909786],
       [-0.80013059,  0.67657018],
       [ 0.35572917,  0.01495207],
       [ 2.00583058, -0.15242439]])

In [28]:
from sklearn.decomposition import PCA

In [29]:
pca = PCA()

In [30]:
pca.fit_transform(scaled_data)                # Line 2

array([[-1.56142916, -0.53909786],
       [-0.80013059,  0.67657018],
       [ 0.35572917,  0.01495207],
       [ 2.00583058, -0.15242439]])

In [32]:
# Here in Line 1 and Line 2 we are getting same data by doing both methods.

In [34]:
pd.DataFrame(data=pca.fit_transform(scaled_data), columns = ["PC1","PC2"])   

PC1       PC2
0 -1.561429 -0.539098
1 -0.800131  0.676570
2  0.355729  0.014952
3  2.005831 -0.152424

In [35]:
pca.explained_variance_ratio_

array([0.90352119, 0.09647881])

In [36]:
sum(pca.explained_variance_ratio_)

1.0

In [37]:
# Here we select PC1 because it is providing more information.

In [38]:
df = pd.read_csv("https://gist.githubusercontent.com/yifancui/e1d5ce0ba59ba0c275c0e2efed542a37/raw/dde7dbca24429542ff78964b83aaf064142dd771/data.csv")

In [39]:
df

Id number       RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  \
0            1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   
1            2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   
2            3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   
3            4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   
4            5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   
..         ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   
209        210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   
210        211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   
211        212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0   
212        213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0   
213        214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0   

     Type of glass  
0                1  
1                1  
2                1  
3                1  
4                1  
..             ...  
209              7  
210              7  
211              7  
212              7  
213              7  

[214 rows x 11 columns]

In [40]:
df.shape

(214, 11)

In [41]:
df.head(2)

Id number       RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  \
0          1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0   
1          2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0   

   Type of glass  
0              1  
1              1

In [43]:
df = df.drop(["Id number", "Type of glass"],axis=1)

In [45]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [48]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [49]:

scaled_df=scaler.fit_transform(df)

In [50]:

scaled_df

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [51]:
pca1=PCA()
pca_data=pca1.fit_transform(scaled_df)

In [52]:
pd.DataFrame(pca_data)

0         1         2         3         4         5         6  \
0    1.151140 -0.529488 -0.372096  1.728901 -0.251936  0.340210 -0.395600   
1   -0.574137 -0.759788 -0.556708  0.760232 -0.257071 -0.115960 -0.024158   
2   -0.940160 -0.929836 -0.554907  0.206254 -0.237506  0.126630 -0.367518   
3   -0.142083 -0.961677 -0.117125  0.415724 -0.476299  0.285805 -0.052497   
4   -0.351092 -1.091249 -0.485079  0.069102 -0.432090  0.298032  0.158570   
..        ...       ...       ...       ...       ...       ...       ...   
209 -2.383835  3.061677  0.090445 -0.376611  0.103227  0.231162 -1.320186   
210 -2.397652  3.108236 -1.117502  0.288454  0.624723  0.618056  0.582361   
211 -1.680246  3.284823 -0.930349 -0.171014  0.451687  1.247320  0.674122   
212 -2.369748  2.756873 -1.234701 -0.525285  0.515008  1.003352  0.678899   
213 -2.262649  3.028592 -0.890845 -0.414491  0.505474  1.213617  0.462461   

            7         8  
0   -0.197160  0.016346  
1   -0.284214 -0.010790  
2   -0.095941  0.021640  
3   -0.002959  0.092035  
4   -0.191316  0.002315  
..        ...       ...  
209  0.189401 -0.028657  
210  0.131651 -0.013663  
211 -0.891710  0.046284  
212  0.074460 -0.027301  
213  0.063315 -0.019450  

[214 rows x 9 columns]

In [53]:
pca1.explained_variance_ratio_

array([2.79018192e-01, 2.27785798e-01, 1.56093777e-01, 1.28651383e-01,
       1.01555805e-01, 5.86261325e-02, 4.09953826e-02, 7.09477197e-03,
       1.78757536e-04])

In [54]:
max(pca1.explained_variance_ratio_)

0.27901819179456466

In [55]:
min(pca1.explained_variance_ratio_)

0.00017875753590172562

In [56]:
sum(pca1.explained_variance_ratio_)

0.9999999999999999

In [57]:
sorted(pca1.explained_variance_ratio_)

[0.00017875753590172562,
 0.007094771974823585,
 0.04099538259055578,
 0.0586261325220868,
 0.10155580523615619,
 0.12865138291980238,
 0.1560937771094047,
 0.22778579831670417,
 0.27901819179456466]

In [58]:

sorted(pca1.explained_variance_ratio_,reverse=True)

[0.27901819179456466,
 0.22778579831670417,
 0.1560937771094047,
 0.12865138291980238,
 0.10155580523615619,
 0.0586261325220868,
 0.04099538259055578,
 0.007094771974823585,
 0.00017875753590172562]

In [59]:
#from the entire data we are extracting 95% info
sum(sorted(pca1.explained_variance_ratio_,reverse=True)[:6])*100

95.17310878987189

In [60]:
#from the entire data we are extracting 99% info
sum(sorted(pca1.explained_variance_ratio_,reverse=True)[:7])*100

99.27264704892747

In [61]:
var=pca1.explained_variance_ratio_

In [62]:

var

array([2.79018192e-01, 2.27785798e-01, 1.56093777e-01, 1.28651383e-01,
       1.01555805e-01, 5.86261325e-02, 4.09953826e-02, 7.09477197e-03,
       1.78757536e-04])

In [63]:
np.cumsum(var)

array([0.27901819, 0.50680399, 0.66289777, 0.79154915, 0.89310496,
       0.95173109, 0.99272647, 0.99982124, 1.        ])

In [64]:
plt.plot(np.cumsum(var))
plt.show()

In [65]:
# Sunny PCA Referal :-- https://github.com/sunnysavita10/PCA